/*
From the following tables write a SQL query to calculate the total order amount generated by a salesperson. Salespersons should be from the cities where the customers reside. 
Return salesperson name, city and total order amount.
*/
SELECT s.name, s.city, subquery.total_amt
FROM Salesman s
JOIN (
    SELECT salesman_id, SUM(purch_amt) AS total_amt
    FROM Orders
    GROUP BY salesman_id
) subquery ON subquery.salesman_id = s.salesman_id
WHERE s.city IN (SELECT DISTINCT city FROM Customer);
